function randList() {

	var all_list_items = [
		'A boy\'s name', 
		'A river', 
		'An animal', 
		'Things that are cold', 
		'Insects', 
		'TV Shows', 
		'Things that grow', 
		'Fruits', 
		'Things that are black', 
		'School subjects', 
		'Movie titles', 
		'Musical Instruments', 
		'Authors', 
		'Bodies of water', 
		'A bird', 
		'Countries', 
		'Cartoon characters', 
		'Holidays', 
		'Things that are square', 
		'Clothing', 
		'A relative', 
		'Games', 
		'Sports Stars', 
		'School supplies', 
		'Things that are hot', 
		'Heroes', 
		'A girl\'s name', 
		'Fears', 
		'TV Stars', 
		'Colours', 
		'A fish', 
		'Fruits', 
		'Provinces or States (US)', 
		'Sports equipment', 
		'Tools', 
		'Breakfast foods', 
		'Gifts', 
		'Flowers', 
		'Ice cream flavours', 
		'A drink', 
		'Toys', 
		'Cities', 
		'Things in the kitchen', 
		'Ocean things', 
		'Nicknames', 
		'Hobbies', 
		'Parts of the body', 
		'Sandwiches', 
		'Items in a catalogue', 
		'World leaders/Politicians', 
		'School subjects', 
		'Excuses for being late', 
		'Things that jump/bounce', 
		'Things in a park', 
		'Foreign cities', 
		'Stones/Gems', 
		'Musical instruments', 
		'Nicknames', 
		'Things in the sky', 
		'Pizza toppings', 
		'Colleges/Universities', 
		'Fish', 
		'Countries', 
		'Things that have spots', 
		'Historical Figures', 
		'Something you\'re afraid of', 
		'Terms of endearment', 
		'Items in this room', 
		'Drugs that are abused', 
		'Fictional characters', 
		'Menu items', 
		'Magazines', 
		'Capitals', 
		'Kinds of candy', 
		'Items you save up to buy', 
		'Footwear', 
		'Something you keep hidden', 
		'Items in a suitcase', 
		'Things with tails', 
		'Crimes', 
		'Things that are sticky', 
		'Awards/ceremonies', 
		'Cars', 
		'Spices/Herbs', 
		'Bad habits', 
		'Cosmetics/Toiletries', 
		'Celebrities', 
		'Cooking utensils', 
		'Reptiles/Amphibians', 
		'Parks', 
		'Leisure activities', 
		'Things you\'re allergic to', 
		'Restaurants', 
		'Notorious people', 
		'Fruits', 
		'Things in a medicine cabinet', 
		'Household chores', 
		'Bodies of water', 
		'Authors', 
		'Halloween costumes', 
		'Weapons', 
		'Things that are round', 
		'Words associated with exercise', 
		'Sports', 
		'Song titles', 
		'Parts of the body', 
		'Ethnic foods', 
		'Things you shout', 
		'Birds', 
		'Ways to get from here to there', 
		'Items in a kitchen', 
		'Villains', 
		'Flowers', 
		'Things you replace', 
		'Baby foods', 
		'Famous duos and trios', 
		'Things found in a desk', 
		'Vacation spots', 
		'Diseases', 
		'Words associated with money', 
		'Items in a vending machine', 
		'Movie Titles', 
		'Games', 
		'Things you wear', 
		'Beers', 
		'Things at a circus', 
		'Vegetables', 
		'Things you throw away', 
		'Occupations', 
		'Appliances', 
		'Cartoon characters', 
		'Types of drinks', 
		'Musical groups', 
		'Store names', 
		'Things at a football game', 
		'Trees', 
		'Personality traits', 
		'Video games', 
		'Electronic gadgets', 
		'Board games', 
		'Things that use a remote', 
		'Card games', 
		'Internet lingo', 
		'Offensive words', 
		'Wireless things', 
		'Computer parts', 
		'Software', 
		'Websites', 
		'Game terms', 
		'Things in a grocery store', 
		'Reasons to quit your job', 
		'Things that have stripes', 
		'Tourist attractions', 
		'Diet foods', 
		'Things found in a hospital', 
		'Food/Drink that is green', 
		'Weekend Activities', 
		'Acronyms', 
		'Seafood', 
		'Christmas songs', 
		'Words ending in \'n\'', 
		'Words with double letters', 
		'Children\'s books', 
		'Things found at a bar', 
		'Sports played outdoors', 
		'Names used in songs', 
		'Foods you eat raw', 
		'Places in Europe', 
		'Olympic events', 
		'Things you see at the zoo', 
		'Math terms', 
		'Animals in books or movies', 
		'Things to do at a party', 
		'Kinds of soup', 
		'Things found in New York', 
		'Things you get tickets for', 
		'Things you do at work', 
		'Foreign words used in English', 
		'Things you shouldn\'t touch', 
		'Spicy foods', 
		'Things at a carnival', 
		'Things you make', 
		'Places to hangout', 
		'Animal noises', 
		'Computer programs', 
		'Honeymoon spots', 
		'Things you buy for kids', 
		'Things that can kill you', 
		'Reasons to take out a loan', 
		'Words associated with winter', 
		'Things to do on a date', 
		'Historic events', 
		'Things you store items in', 
		'Things you do everyday', 
		'Things you get in the mail', 
		'Things you save up to buy', 
		'Things you sit on', 
		'Reasons to make a phone call', 
		'Types of weather', 
		'Titles people can have', 
		'Things that have buttons', 
		'Items you take on a road trip', 
		'Things that have wheels', 
		'Reasons to call 911', 
		'Things that make you smile', 
		'Ways to kill time', 
		'Things that can get you fired', 
		'Hobbies', 
		'Holiday Activities', 
		"Old-fashioned boy's name", 
		'Items that are frozen', 
		'Television shows from 2000', 
		'Rivers', 
		'Vegetables', 
		'Things that are yellow', 
		'Trees', 
		'Marching band instruments', 
		'College subjects', 
		'Dishes made from pasta', 
		'Books about animals', 
		'Insects', 
		'Types of sports', 
		'Poems', 
		'Parts of the human body', 
		"Old fashioned girl's name", 
		'Ethnic dishes', 
		'Types of transportation', 
		'School supplies', 
		'Items found in a library', 
		'Types of birds', 
		'Flowers', 
		'Types of shoes', 
		'Halloween costumes', 
		'Foods found in a submarine', 
		'Politicians', 
		'Reasons a child is grounded', 
		'Television actors', 
		'Semi-precious gemstones', 
		'Country foods', 
		'Types of balls', 
		'Animals in zoos', 
		'Things in the circus', 
		'Things found in a park', 
		'Types of cats', 
		'Book authors', 
		'Things that are round', 
		'Types of clothing', 
		'Games played at recess', 
		'Mammals', 
		'Types of relatives', 
		'Holidays around the world', 
		'Fruits', 
		'Things found in a forest', 
		'Colours', 
		'Sports stars', 
		'Restaurants', 
		'Villains', 
		'Toys', 
		'Weapons', 
		'Things that are square', 
		'Things used by a bodybuilder', 
		'Things in the bathroom', 
		'Types of exercises', 
		'Desserts', 
		'Newspapers', 
		'Things found in space', 
		'States', 
		'Tools', 
		'Things found in a cafeteria', 
		'Things found on a farm', 
		'Fears', 
		'Sweet things', 
		'Dental procedures', 
		'Perfumes', 
		'Types off candy', 
		'Accessories', 
		'Things used by the handicapped', 
		'Sounds animals make', 
		'Things that are hot', 
		'Breakfast foods', 
		'Graduation gifts', 
		'Types of drinks', 
		'Things found in the ocean', 
		'Hobbies', 
		'Child actresses', 
		'Types of cheese', 
		'Types of transportation', 
		'Reasons to be late', 
		'Professions', 
		'Things that are cold', 
		'Toppings for pizza', 
		'Colleges', 
		'Things with spots', 
		'Things from the Civil War', 
		'Items in a dresser drawer', 
		'Ways to relax', 
		'Ethnicities', 
		'Things found in the sky', 
		'Figures from history', 
		'Types of drugs', 
		'Types of bread', 
		'Fictional characters', 
		'Items on a lunch menu', 
		'Magazines', 
		'State capitals', 
		'Things with tails', 
		'Crimes', 
		'Vanilla items', 
		'Types of popcorn', 
		'Large ticket items', 
		"Items in Grandma's kitchen", 
		'Dog toys', 
		'Items found in the backyard', 
		'Sticky things', 
		'Types of vehicles', 
		'Herbs', 
		'Cosmetics', 
		'Utensils for cooking', 
		'Bad habits', 
		'Scandals', 
		'Reptiles', 
		'Leisure activities', 
		'Monthly expenses', 
		'Things found at a construction site'
		];

	var list_twelve = [];
	while ((list_twelve).length < 12) {
		//picks random item from list
		var list_item = all_list_items[Math.floor(Math.random() * all_list_items.length)];
		//check if it's already been picked
		if (list_twelve.indexOf(list_item) >= 0) {
    		continue;
    	//otherwise add it to the new list of twelve
		} else {
			list_twelve.push(list_item)
		}
	}

	//clears the existing list inside box
	document.getElementById('randlist').innerHTML = "" 

	//adds the new list as listitems within html
	for(var i = 0; i < list_twelve.length; i++) {
		document.getElementById('randlist').innerHTML += ('<li>'+list_twelve[i]+'</li>');
	}
}